NODE_ENV: development
HOST_ADDR: http://localhost:3000
APP_PORT: 3000

GITHUB_API_URL: https://api.github.com

ADMIN_USERS:
  - prayerslayer

# Database configuration
# sqlite or postgres
DB_DRIVER: sqlite
#DB_NAME: postgres
#DB_USER: postgres
#DB_PASS: postgres
#DB_HOST: 192.168.99.100
#DB_PORT: 5432
#DB_SCHEMA: zappr
SQLITE_FILE: ./status.sqlite

# Logging level
LOG_LEVEL: debug
